Update mosbasic
Moved configuration checks around for module support.  Module setup comes from the Runme1st configuration script.  mosbasic only will check to make sure these things are setup and if so sanity check them now.

diff --git a/mosbasic b/mosbasic
--- a/mosbasic
+++ b/mosbasic
@@ -129,35 +129,32 @@ fi
 
 #Check for outside module support
 if [ ! -s "$LOCALCONF/MOSBasic/.modules" ]; then
-	echo "Will you be using outside modules to help with lookups of student IDs"
-	echo "or other data?  OPTIONS are: iiq, none, or custom  More info can be found"
-	echo "in the readme.  DEFAULT is none"
-	
-	read GotModules
-	
-	if [ -z "$GotModules" ]; then
-		echo "GotModules=none" > "$LOCALCONF/MOSBasic/.modules"
-	elif [ "$GotModules" = "iiq" ]; then
-		echo "Enabling IncidentIQ support."
-		echo "GotModules=iiq" > "$LOCALCONF/MOSBasic/.modules"
-				
-		if [ ! -s "$LOCALCONF/.incidentIQ" ]; then
-			echo "HEADS UP, no local incidentIQ API info is available."
-			echo "SEE README FOR MORE INFO."
-		else
-			source $LOCALCONF/.incidentIQ
-			IIQAuth=$(echo "Authorization: Bearer $apitoken")
-		fi
-		
-	elif [ "$GotModules" = "other" ]; then
-		echo "This feature is not supported, YET.  Setting to none.."
-		echo "GotModules=none" > "$LOCALCONF/MOSBasic/.modules"
+	sudo "Modules doesn't seem to be setup."
+	echo "sudo $BAGCLI_WORKDIR/RUNME1st_CONFIGSCRIPT.sh to setup."
+	echo "SEE README FOR MORE INFO."
+	exit 1
+fi
+
+#Sanity check what is listed in the Modules support
+#bracket.
+source 	"$LOCALCONF"/MOSBasic/.modules
+if [ "$GotModules" = "iiq" ]; then
+	if [ ! -s "$LOCALCONF/.incidentIQ" ]; then
+		echo "HEADS UP, no local incidentIQ API info is available."
+		echo "SEE README FOR MORE INFO."
 	else
-		echo "Whatever you typed ($GotModules) I don't know what that is."
-		echo "Epic Fail"
-		exit 1
+		source $LOCALCONF/.incidentIQ
+		IIQAuth=$(echo "Authorization: Bearer $apitoken")
 	fi
-fi	
+	
+elif [ "$GotModules" = "other" ]; then
+	echo "This feature is not supported, YET.  Setting to none.."
+else
+	echo "Whatever you have in "$LOCALCONF"/MOSBasic/.modules ($GotModules) I don't know what that is."
+	echo "Epic Fail"
+	exit 1
+fi
+
 
 #######################################
 # Do we have cache'd data about iPads
