Lost Mode on, off, and play sound
Added code for lost mode on, off, and play sound.

You must give asset tag, but if you don't know which you can always do mosbasic info <username> to get that info.

diff --git a/mosbasic b/mosbasic
--- a/mosbasic
+++ b/mosbasic
@@ -39,6 +39,10 @@ Version: $(cat $BAGCLI_WORKDIR/VERSION)
 https://github.com/JCSmillie/MOSBasic
 Usage: $cli_name [command]
 Commands:
+  lostmodeon    Give single asset tag.  Will enable lost mode with default message.
+  lostmodeoff   Give single asset tag.  Will disable lost mode.
+  annoy         Give single asset tag.  Will play sound.  If device is not in lost mode
+                will also enable it. 
   ioswipe		Give single asset tag.  Will Limbo and Wipe that iPad.
   			**NOTE** Wipe will fail if device is not on Wifi.
   ioswipe --scan	Scan multiple devices.  When done hit enter to give a blank.
@@ -63,8 +67,36 @@ Commands:
   && echo "cp $BAGCLI_WORKDIR/config.template $BAGCLI_WORKDIR/config and adjust." \
   && exit 1
 
+###############################
+#   Check Condtions to work   #
+###############################
+# #See if we know who ran this otherwise note it as Console did it
+if [ -z "$RUNNING_USER" ]; then
+	RUNNING_USER="<<Console>>"
+fi
+
 #export $(cat "$BAGCLI_WORKDIR/config" | xargs)
 source "$BAGCLI_WORKDIR/config"
+
+#Make sure our log directory is there
+if [ ! -d "$LOCALCONF/MOSBasic" ]; then
+	echo "Directory for log files and nat not found.  Creating. $LOCALCONF/MOSBasic"
+	mkdir "$LOCALCONF/MOSBasic"
+fi
+
+#First Make sure we have what we need
+if [ ! -s "$TEMPOUTPUTFILE_MERGEDIOS" ]; then
+	log_line "$TEMPOUTPUTFILE_MERGEDIOS is missing.  Must grab NOW."
+	"$BAGCLI_WORKDIR/commands/mosdatadump-iOS.sh"
+fi
+
+if [ ! -s "$TEMPOUTPUTFILE_Users" ]; then
+	log_line "$TEMPOUTPUTFILE_Users is missing.   Must grab NOW."
+	"$BAGCLI_WORKDIR/commands/mosdatadump-USERS.sh"
+	exit 1
+fi
+
+
 
 
 echo "Variable 1-> $1"
@@ -85,7 +117,16 @@ info)
 	;;
 ioswipe)
 	"$BAGCLI_WORKDIR/commands/iosLimboNWipe.sh" "$2" "$3"
-	;;	 	
+	;;
+lostmodeon)
+	"$BAGCLI_WORKDIR/commands/lostmodefun.sh" "--enable" "$2"
+	;;	 
+lostmodeoff)
+	"$BAGCLI_WORKDIR/commands/lostmodefun.sh" "--disable" "$2"
+	;;	 
+annoy)
+	"$BAGCLI_WORKDIR/commands/lostmodefun.sh" "--sound" "$2"
+	;;	 		
   *)
     cli_help
     ;;
